---@type ShopClothingDataConfig
return {
    categories = {
        'shirts',
        'pants',
        'shoes',
        'masks',
        'hats',
        'chains',
        'arms',
        'vests',
        'glasses',
        'watches',
        'bracelets',
        'bags',
        'outfits',
    },
    components = {
        ['head'] = 0,
        ['berd'] = 1,
        ['hair'] = 2,
        ['uppr'] = 3,
        ['lowr'] = 4,
        ['hand'] = 5,
        ['feet'] = 6,
        ['teef'] = 7,
        ['accs'] = 8,
        ['task'] = 9,
        ['decl'] = 10,
        ['jbib'] = 11,
    },
    props = {
        ['hat'] = 0,
        ['eyes'] = 1,
        ['ears'] = 2,
        ['watch'] = 6,
        ['bracelet'] = 7,
    },
    defaults = {
        ['masks'] = {'empty_mask'},
        ['shirts'] = {'empty_jacket'},
        ['pants'] = {'empty_pants'},
        ['shoes'] = {'empty_shoes'},
        ['arms'] = {'empty_hands'},
        ['hats'] = {'empty_hat'},
        ['watches'] = {'empty_watch'},
        ['bracelets'] = {'empty_bracelet'},
        ['bags'] = {'empty_bag'},
        ['glasses'] = {'empty_glasses'},
        ['vests'] = {'empty_vest'},
        ['chains'] = {'empty_chain'},
    },
    tattooZones = {
        'torso',
        'head',
        'left_arm',
        'right_arm',
        'left_leg',
        'right_leg',
    },
    bodyTypes = {
        {
            id = 'male_default',
            label = 'Default',
            armTypes = {
                'full_body',
                'long',
                'short',
                'half',
                'full_neck',
                'short_chest',
                'fat_full_body',
                'skinny_full_body',
            },
            male = true,
        },
        {
            id = 'male_skinny',
            label = 'Skinny',
            armTypes = {},
            male = true,
        },
        {
            id = 'male_fat',
            label = 'Fat',
            armTypes = {},
            male = true,
        },
        {
            id = 'female_default',
            label = 'Default',
            armTypes = {
                'full_body',
                'long',
                'short',
                'sideways',
                'short_chest',
            },
            male = false,
        },
        {
            id = 'female_skinny',
            label = 'Skinny',
            armTypes = {},
            male = false,
        }
    },
}