return {
	components = {
		[1] = {
			fov = 30,
			rotation = vec3(0, 0, 145),
			zPos = 0.65,
			name = 'Masks',
		},
		[3] = {
			fov = 20,
			rotation = vec3(0, 0, 250),
			zPos = -0.09,
			name = 'Torsos',
			rect = {
				{
					x = 0.5,
					y = 0.295,
					width = 1.0,
					height = 0.19,
				},
				{
					x = 0.83,
					y = 0.5,
					width = 0.45,
					height = 1.0,
				},
			},
		},
		[4] = {
			fov = 60,
			rotation = vec3(0, 0, 180),
			zPos = -0.46,
			name = 'Legs',
		},
		[5] = {
			fov = 45,
			rotation = vec3(0, 0, 0),
			zPos = 0.3,
			name = 'Bags',
		},
		[6] = {
			fov = 40,
			rotation = vec3(0, 0, 145),
			zPos = -0.85,
			name = 'Shoes',
		},
		[7] = {
			fov = 45,
			rotation = vec3(0, 0, 180),
			zPos = 0.3,
			name = 'Accessories',
		},
		[8] = {
			fov = 45,
			rotation = vec3(0, 0, 180),
			zPos = 0.3,
			name = 'Undershirts',
		},
		[9] = {
			fov = 60,
			rotation = vec3(0, 0, 180),
			zPos = 0.26,
			name = 'Body Armors',
		},
		[11] = {
			fov = 55,
			rotation = vec3(0, 0, 180),
			zPos = 0.26,
			name = 'Tops',
		},
	},
	props = {
		[0] = {
			fov = 30,
			rotation = vec3(0, 0, 120),
			zPos = 0.75,
			name = 'Hats',
		},
		[1] = {
			fov = 20,
			rotation = vec3(0, 0, 120),
			zPos = 0.7,
			name = 'Glasses',
		},
		[2] = {
			fov = 20,
			rotation = vec3(0, 0, 237.5),
			zPos = 0.675,
			name = 'Ears',
		},
		[6] = {
			fov = 20,
			rotation = vec3(0, 0, 59),
			zPos = 0.03,
			name = 'Watches',
			rect = {
				{
					x = 0.5,
					y = 0.575,
					width = 0.05,
					height = 0.2,
				}
			}
		},
		[7] = {
			fov = 20,
			rotation = vec3(0, 0, 240),
			zPos = 0.03,
			name = 'Bracelets',
			rect = {
				{
					x = 0.53,
					y = 0.275,
					width = 0.15,
					height = 0.8,
				}
			}
		},
	},
	categories = {
		['shirts'] = {
			components = {'jbib', 'accs'},
			needsArmType = true,
		},
		['pants'] = {
			components = {'lowr', 'decl'},
		},
		['shoes'] = {
			components = {'feet'},
		},
		['masks'] = {
			components = {'berd'},
		},
		['hats'] = {
			props = {'hat'},
		},
		['chains'] = {
			components = {'teef'},
		},
		['vests'] = {
			components = {'task'},
		},
		['glasses'] = {
			props = {'eyes'}
		},
		['watches'] = {
			props = {'watch'},
		},
		['bracelets'] = {
			props = {'bracelet'},
		},
		['bags'] = {
			components = {'hand'},
		},
	},
	rarities = {
		'common',
		'uncommon',
		'rare',
		'epic',
		'legendary',
		'mythical',
		'gang',
		'event',
		'battlepass',
	},
	editableArmTypes = {
		['male'] = 'male_default',
		['female'] = 'female_default',
	},
	ignoredEditArms = {
		'fat_full_body',
    	'skinny_full_body',
	},
	---@type ShopDebugVehicleColour[]
	vehicleColours = {
		{ id = 0, name = 'BLACK' },
		{ id = 1, name = 'GRAPHITE' },
		{ id = 2, name = 'BLACK_STEEL' },
		{ id = 3, name = 'DARK_SILVER' },
		{ id = 4, name = 'SILVER' },
		{ id = 5, name = 'BLUE_SILVER' },
		{ id = 6, name = 'ROLLED_STEEL' },
		{ id = 7, name = 'SHADOW_SILVER' },
		{ id = 8, name = 'STONE_SILVER' },
		{ id = 9, name = 'MIDNIGHT_SILVER' },
		{ id = 10, name = 'CAST_IRON_SIL' },
		{ id = 11, name = 'ANTHR_BLACK' },
		{ id = 27, name = 'RED' },
		{ id = 28, name = 'TORINO_RED' },
		{ id = 29, name = 'FORMULA_RED' },
		{ id = 30, name = 'BLAZE_RED' },
		{ id = 31, name = 'GRACE_RED' },
		{ id = 32, name = 'GARNET_RED' },
		{ id = 33, name = 'SUNSET_RED' },
		{ id = 34, name = 'CABERNET_RED' },
		{ id = 35, name = 'CANDY_RED' },
		{ id = 36, name = 'SUNRISE_ORANGE' },
		{ id = 37, name = 'GOLD' },
		{ id = 38, name = 'ORANGE' },
		{ id = 49, name = 'DARK_GREEN' },
		{ id = 50, name = 'RACING_GREEN' },
		{ id = 51, name = 'SEA_GREEN' },
		{ id = 52, name = 'OLIVE_GREEN' },
		{ id = 53, name = 'BRIGHT_GREEN' },
		{ id = 54, name = 'PETROL_GREEN' },
		{ id = 61, name = 'GALAXY_BLUE' },
		{ id = 62, name = 'DARK_BLUE' },
		{ id = 63, name = 'SAXON_BLUE' },
		{ id = 64, name = 'BLUE' },
		{ id = 65, name = 'MARINER_BLUE' },
		{ id = 66, name = 'HARBOR_BLUE' },
		{ id = 67, name = 'DIAMOND_BLUE' },
		{ id = 68, name = 'SURF_BLUE' },
		{ id = 69, name = 'NAUTICAL_BLUE' },
		{ id = 70, name = 'ULTRA_BLUE' },
		{ id = 71, name = 'PURPLE' },
		{ id = 72, name = 'SPIN_PURPLE' },
		{ id = 73, name = 'RACING_BLUE' },
		{ id = 74, name = 'LIGHT_BLUE' },
		{ id = 88, name = 'YELLOW' },
		{ id = 89, name = 'RACE_YELLOW' },
		{ id = 90, name = 'BRONZE' },
		{ id = 91, name = 'FLUR_YELLOW' },
		{ id = 92, name = 'LIME_GREEN' },
		{ id = 94, name = 'UMBER_BROWN' },
		{ id = 95, name = 'CREEK_BROWN' },
		{ id = 96, name = 'CHOCOLATE_BROWN' },
		{ id = 97, name = 'MAPLE_BROWN' },
		{ id = 98, name = 'SADDLE_BROWN' },
		{ id = 99, name = 'STRAW_BROWN' },
		{ id = 100, name = 'MOSS_BROWN' },
		{ id = 101, name = 'BISON_BROWN' },
		{ id = 102, name = 'WOODBEECH_BROWN' },
		{ id = 103, name = 'BEECHWOOD_BROWN' },
		{ id = 104, name = 'SIENNA_BROWN' },
		{ id = 105, name = 'SANDY_BROWN' },
		{ id = 106, name = 'BLEECHED_BROWN' },
		{ id = 107, name = 'CREAM' },
		{ id = 111, name = 'WHITE' },
		{ id = 112, name = 'FROST_WHITE' },
		{ id = 135, name = 'HOT PINK' },
		{ id = 136, name = 'SALMON_PINK' },
		{ id = 137, name = 'PINK' },
		{ id = 138, name = 'BRIGHT_ORANGE' },
		{ id = 141, name = 'MIDNIGHT_BLUE' },
		{ id = 142, name = 'MIGHT_PURPLE' },
		{ id = 143, name = 'WINE_RED' },
		{ id = 145, name = 'BRIGHT_PURPLE' },
		{ id = 146, name = 'VERY_DARK_BLUE' },
		{ id = 147, name = 'BLACK_GRAPHITE' },
		{ id = 150, name = 'LAVA_RED' },
	},
}