---@type HopOutSharedConfig
return {
    colors = {
        ['Red'] = {
            blip = 1,
            hud = 6,
            vehicle = 27,
            hex = '#FF0000',
        },
        ['Orange'] = {
            blip = 47,
            hud = 15,
            vehicle = 38,
            hex = '#FFa500',
        },
        ['Yellow'] = {
            blip = 5,
            hud = 12,
            vehicle = 88,
            hex = '#FFE40C',
        },
        ['Green'] = {
            blip = 2,
            hud = 18,
            vehicle = 128,
            hex = '#00FF00',
        },
        ['Blue'] = {
            blip = 3,
            hud = 9,
            vehicle = 83,
            hex = '#0000FF',
        },
        ['Violet'] = {
            blip = 7,
            hud = 21,
            vehicle = 71,
            hex = '#8F00FF',
        },
        ['Pink'] = {
            blip = 8,
            hud = 24,
            vehicle = 135,
            hex = '#FF69B4',
        },
        ['Cyan'] = {
            blip = 30,
            hud = 10,
            vehicle = 70,
            hex = '#00E5FF',
        },
        ['White'] = {
            blip = 4,
            hud = 1,
            vehicle = 111,
            hex = '#FFFFFF',
        },
        ['Brown'] = {
            blip = 31,
            hud = 106,
            vehicle = 96,
            hex = '#A0522D',
        },
    },
    rifleName = 'WEAPON_CARBINERIFLE',
    pistolName = 'WEAPON_COMBATPISTOL',
    meleeName = 'WEAPON_STONE_HATCHET',
    smokeGrenadeName = 'WEAPON_SMOKEGRENADE',
    smokeGrenadeCount = 1,
    numArmors = 5,
    numMedKits = 15,
    pistolOnlyRounds = { 1, 5 }, -- first to 5: halftime after round 4, so round 5 opens the second half
    multiTeamsPistolOnlyRounds = { 1, 6, 11, 16 },
    scoreboardDisplayTimeMsec = 13000,
    scoreboardSlowMoIntroMsec = 3000,
    switchSidesDurationMsec = 5000,
    switchSideOffsets = {
        0,
        0.8,
        -0.8,
        1.6,
        -1.6,
        2.4,
        -2.4,
        3.2,
        -3.2,
        4.0,
    },
    eloProgressionFadeDurationMsec = 500,
    eloProgressionDurationMsec = 7000,
    vehicleModels = {
        'issi7',
        'jugular',
        'issi7',
    },
    centerVehicleModel = 'jugular',
    jumpoutsVehicleModels = {
        'jugular',
    },
    timeoutDurationMsec = 150000,
    winnerPreviewDurationMsec = 15000,
    requestDoubleDurationMsec = 15000,
}